import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { formatAmountPlain } from '@/lib/finance/formatters';
import {
  buildInvoiceHTML,
  buildStatementHTML,
  buildStatementRows,
} from '@/lib/finance/invoiceHtml';
import { LOGO_BASE64 } from '@/lib/finance/logoBase64';
import { fetchClientInvoices } from '@/lib/finance/queries';
import { requireSupabase } from '@/lib/supabase';
import type { FinanceReportData, InvoiceWithDetails } from '@/types/finance';

/** Banking details for invoice PDFs — update account number here. */
export const BANKING = {
  bank: 'FNB',
  accountName: 'Diedericks Dobermanns',
  accountNo: 'XXXXXXXX',
  branch: '250655',
} as const;

function generateIncomeStatementHTML(data: FinanceReportData): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Georgia, serif; background: #fff; color: #1a1a1a; padding: 40px; }
        h1 { font-size: 24px; letter-spacing: 4px; text-transform: uppercase; }
        h2 { font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: #666; }
        .period { color: #888; font-size: 12px; margin-bottom: 32px; }
        .section-header { font-size: 11px; font-weight: bold; letter-spacing: 2px;
                          text-transform: uppercase; border-bottom: 1px solid #C4A35A;
                          padding-bottom: 4px; margin-top: 24px; color: #C4A35A; }
        .line-item { display: flex; justify-content: space-between; padding: 4px 0;
                     font-size: 13px; }
        .line-item.indent { padding-left: 16px; }
        .total-line { display: flex; justify-content: space-between; font-weight: bold;
                      border-top: 1px solid #333; padding-top: 6px; margin-top: 4px; }
        .net-profit { font-size: 16px; font-weight: bold; color: #C4A35A;
                      border-top: 2px solid #C4A35A; border-bottom: 2px solid #C4A35A;
                      padding: 10px 0; margin-top: 16px; }
        .footer { margin-top: 48px; font-size: 10px; color: #999;
                  border-top: 1px solid #eee; padding-top: 12px; }
        .amount { font-variant-numeric: tabular-nums; }
      </style>
    </head>
    <body>
      <h1>Diedericks Dobermanns</h1>
      <h2>Income Statement</h2>
      <div class="period">Period: ${data.periodLabel}</div>

      <div class="section-header">Income</div>
      ${data.incomeLines
        .map(
          (l) => `
        <div class="line-item indent">
          <span>${l.label}</span>
          <span class="amount">R ${formatAmountPlain(l.amount)}</span>
        </div>`,
        )
        .join('')}
      <div class="total-line">
        <span>TOTAL INCOME</span>
        <span class="amount">R ${formatAmountPlain(data.totalIncome)}</span>
      </div>

      <div class="section-header" style="margin-top:24px">Expenses</div>
      ${data.expenseLines
        .map(
          (l) => `
        <div class="line-item indent">
          <span>${l.label}</span>
          <span class="amount">R ${formatAmountPlain(l.amount)}</span>
        </div>`,
        )
        .join('')}
      <div class="total-line">
        <span>TOTAL EXPENSES</span>
        <span class="amount">R ${formatAmountPlain(data.totalExpenses)}</span>
      </div>

      <div class="net-profit" style="display:flex;justify-content:space-between">
        <span>NET PROFIT</span>
        <span class="amount">R ${formatAmountPlain(data.netProfit)}</span>
      </div>
      <div class="line-item" style="color:#666;font-size:12px;margin-top:8px">
        <span>Profit Margin</span>
        <span>${data.profitMargin.toFixed(1)}%</span>
      </div>

      <div class="footer">
        Generated by Diedericks Dobermanns Management System · ${new Date().toLocaleDateString('en-ZA')}
        · CONFIDENTIAL — For management use only
      </div>
    </body>
    </html>
  `;
}

function generateInvoiceHTML(invoice: InvoiceWithDetails): string {
  return buildInvoiceHTML(invoice, BANKING, LOGO_BASE64);
}

export async function exportFinancePDF(reportData: FinanceReportData) {
  const html = generateIncomeStatementHTML(reportData);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Export Income Statement',
    UTI: 'com.adobe.pdf',
  });
}

export async function exportInvoicePDF(invoice: InvoiceWithDetails) {
  const html = generateInvoiceHTML(invoice);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `Invoice ${invoice.invoice_number}`,
    UTI: 'com.adobe.pdf',
  });
}

export async function exportClientStatement(clientId: string) {
  const supabase = requireSupabase();

  const { data: client, error: clientErr } = await supabase
    .from('users')
    .select('full_name, phone')
    .eq('id', clientId)
    .single();

  if (clientErr) throw new Error(clientErr.message);

  const clientName = client.full_name ?? 'Client';
  const clientContact = client.phone;

  const invoices = (await fetchClientInvoices(clientId)).filter(
    (inv) => inv.status !== 'cancelled',
  );

  const invoiceIds = invoices.map((i) => i.id);
  let payments: Array<{
    payment_date: string;
    amount: number;
    reference: string | null;
    invoice_number: string;
  }> = [];

  if (invoiceIds.length > 0) {
    const { data: payRows, error: payErr } = await supabase
      .from('invoice_payments')
      .select('payment_date, amount, reference, invoice:invoices(invoice_number)')
      .in('invoice_id', invoiceIds);

    if (payErr) throw new Error(payErr.message);

    payments = (payRows ?? []).map((row) => {
      const r = row as Record<string, unknown>;
      const inv = r.invoice as { invoice_number: string } | null;
      return {
        payment_date: r.payment_date as string,
        amount: r.amount as number,
        reference: (r.reference as string | null) ?? null,
        invoice_number: inv?.invoice_number ?? '',
      };
    });
  }

  const rows = buildStatementRows(invoices, payments);
  const html = buildStatementHTML(
    clientName,
    clientContact,
    rows,
    LOGO_BASE64,
  );

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `Statement — ${clientName}`,
    UTI: 'com.adobe.pdf',
  });
}
