// scripts/encode-logo.mjs
// Run once: node scripts/encode-logo.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const logoPath = path.join(__dirname, '..', 'assets', 'icon.png');
const logo = fs.readFileSync(logoPath);
const b64 = `data:image/png;base64,${logo.toString('base64')}`;

const output = `// Auto-generated by scripts/encode-logo.mjs — do not edit manually
// Run: node scripts/encode-logo.mjs to regenerate after logo changes
export const LOGO_BASE64 = '${b64}';
`;

fs.writeFileSync(path.join(__dirname, '..', 'lib', 'finance', 'logoBase64.ts'), output);
console.log('✓ Logo encoded to lib/finance/logoBase64.ts');
