import type { ApplicationFormValues } from '@/components/forms/ApplicationForm/schema';
import type { ApplicationDraft } from '@/hooks/useApplications';

/** Maps validated form values to a Supabase applications insert row. */
export function buildApplicationDraft(values: ApplicationFormValues): ApplicationDraft {
  return {
    user_id: null,
    full_name: values.full_name,
    date_of_birth: values.date_of_birth,
    id_number: values.id_number,
    email: values.email,
    phone: values.phone,
    occupation: values.occupation,
    employer: values.employer || null,
    country: values.country,
    province: values.province || null,
    city: values.city || null,
    address: values.address,
    instagram_handle: values.instagram_handle || null,
    facebook_profile: values.facebook_profile || null,
    home_type: values.home_type,
    has_secure_yard: values.has_secure_yard,
    yard_size: values.yard_size,
    sleeping_arrangement: values.sleeping_arrangement,
    hours_alone_per_day: values.hours_alone_per_day,
    exercise_level: values.exercise_level,
    current_pets: values.current_pets || null,
    children_ages: values.children_ages || null,
    why_dobermann: values.why_dobermann,
    dobermann_experience_level: values.dobermann_experience_level,
    aware_of_dcm: values.aware_of_dcm,
    aware_of_commitment: values.aware_of_commitment,
    aware_of_costs: values.aware_of_costs,
    previous_dog_fate: values.previous_dog_fate || null,
    experience_with_dobermanns: values.experience_with_dobermanns || null,
    vet_name: values.vet_name || null,
    vet_phone: values.vet_phone || null,
    personal_reference_name: values.personal_reference_name || null,
    personal_reference_phone: values.personal_reference_phone || null,
    dog_interest: values.dog_interest,
    specific_dog_id: null,
    litter_interest_id: null,
    purpose: values.purpose,
    preferred_sex: values.preferred_sex,
    preferred_colour: values.preferred_colour,
    tail_preference: values.tail_preference,
    preferred_timeline: values.preferred_timeline,
    budget_range: values.budget_range,
    training_planned: values.training_planned,
    security_requirements: values.security_requirements || null,
    delivery_acknowledged: values.delivery_acknowledged,
    special_requests: values.special_requests || null,
    agreed_no_breeding_rights: values.agreed_no_breeding_rights,
    agreed_right_of_recall: values.agreed_right_of_recall,
    agreed_no_resale: values.agreed_no_resale,
    agreed_welfare_commitment: values.agreed_welfare_commitment,
    agreed_microchip_policy: values.agreed_microchip_policy,
    agreed_to_terms: values.agreed_to_terms,
  };
}
