import type {
  Achievement,
  AppUser,
  Application,
  Contract,
  Dog,
  Enquiry,
  FaqItem,
  GalleryItem,
  Invoice,
  Litter,
  AppSettings,
  BroadcastMessage,
  ClientGroup,
  ClientGroupMember,
  NotificationLog,
  Quote,
  Testimonial,
  TimelineEntry,
  TrainingAvailability,
  TrainingBooking,
  TrainingLog,
  TrainingSessionType,
  Vaccination,
  WaitingListEntry,
} from '@/types/app.types';

/** Returns a YYYY-MM-DD date offset from today (used by training mocks). */
function dayOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/**
 * Seed data used when the app runs in demo mode (no Supabase configured).
 * Photography uses royalty-free Unsplash dog imagery as placeholders; replace
 * with real kennel media once Supabase Storage is connected.
 */

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const MOCK_DOGS: Dog[] = [
  {
    id: 'dog-zeus',
    name: 'Zeus vom Diedericks',
    breed: 'Dobermann',
    colour: 'black/rust',
    sex: 'male',
    date_of_birth: '2021-04-12',
    father_id: null,
    mother_id: null,
    microchip_number: null,
    status: 'breeding_stock',
    category: 'breeding_stock',
    price: null,
    bloodline: 'dominator',
    health_tested: true,
    hip_score: 'HD-A',
    elbow_score: 'ED-0',
    dcm_status: 'clear',
    pedigree_url: null,
    description:
      'A foundation sire of exceptional structure and nerve. Zeus brings the Dominator line\u2019s signature drive balanced with the clear-headed temperament our programme is built on.',
    temperament_notes:
      'Confident, social and biddable. Outstanding off-switch in the home.',
    training_notes: 'IGP-titled foundation. Proofed environmental neutrality.',
    is_featured: true,
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    media: [
      {
        id: 'm-zeus-1',
        dog_id: 'dog-zeus',
        type: 'photo',
        url: img('photo-1605568427561-40dd23c2acea'),
        thumbnail_url: null,
        caption: 'Zeus in profile stance',
        is_primary: true,
        sort_order: 0,
        uploaded_at: '2024-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'dog-nala',
    name: 'Nala vom Diedericks',
    breed: 'Dobermann',
    colour: 'black/rust',
    sex: 'female',
    date_of_birth: '2022-02-08',
    father_id: null,
    mother_id: null,
    microchip_number: null,
    status: 'breeding_stock',
    category: 'breeding_stock',
    price: null,
    bloodline: 'altobello',
    health_tested: true,
    hip_score: 'HD-A',
    elbow_score: 'ED-0',
    dcm_status: 'clear',
    pedigree_url: null,
    description:
      'Elegant Altobello dam with effortless movement and a deeply maternal, stable character.',
    temperament_notes: 'Affectionate, intuitive and protective of her family.',
    training_notes: 'Foundation obedience, advanced socialisation.',
    is_featured: true,
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    media: [
      {
        id: 'm-nala-1',
        dog_id: 'dog-nala',
        type: 'photo',
        url: img('photo-1568572933382-74d440642117'),
        thumbnail_url: null,
        caption: 'Nala',
        is_primary: true,
        sort_order: 0,
        uploaded_at: '2024-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'dog-titan',
    name: 'Titan',
    breed: 'Dobermann',
    colour: 'black/rust',
    sex: 'male',
    date_of_birth: '2024-09-01',
    father_id: 'dog-zeus',
    mother_id: 'dog-nala',
    microchip_number: null,
    status: 'available',
    category: 'training_dog',
    price: 285000,
    bloodline: 'kennel_own',
    health_tested: true,
    hip_score: null,
    elbow_score: null,
    dcm_status: 'clear',
    pedigree_url: null,
    pedigree: {
      sire: { name: 'Zeus vom Diedericks', titles: 'IGP3', registration: 'KUSA DB-2021-0412' },
      dam: { name: 'Nala vom Diedericks', titles: 'BH', registration: 'KUSA DB-2022-0208' },
      sireSire: { name: 'Dominator del Nasi', titles: 'IGP3, KKL1' },
      sireDam: { name: 'Gessica vom Hause Edelstein', titles: 'IGP1' },
      damSire: { name: 'Altobello Quattro', titles: 'IGP3, WUSV' },
      damDam: { name: 'Bella della Valcuvia', titles: 'BH' },
      sireSireSire: { name: 'Furst del Nasi', titles: 'IGP3' },
      sireSireDam: { name: 'Akira del Nasi', titles: 'IGP1' },
      sireDamSire: { name: 'Baron vom Hause Edelstein', titles: 'IGP2' },
      sireDamDam: { name: 'Diva vom Hause Edelstein' },
      damSireSire: { name: 'Pacino Altobello', titles: 'IGP3' },
      damSireDam: { name: 'Roxana Altobello', titles: 'IGP1' },
      damDamSire: { name: 'Nardo della Valcuvia', titles: 'IGP2' },
      damDamDam: { name: 'Sissi della Valcuvia' },
    },
    description:
      'Elite Family Protection prospect from our own line. Currently in the 6-month in-kennel development programme.',
    temperament_notes: 'High drive paired with a remarkable household calm.',
    training_notes: 'Scenario-based protection foundation underway.',
    is_featured: true,
    is_public: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
    media: [
      {
        id: 'm-titan-1',
        dog_id: 'dog-titan',
        type: 'photo',
        url: img('photo-1518717758536-85ae29035b6d'),
        thumbnail_url: null,
        caption: 'Titan',
        is_primary: true,
        sort_order: 0,
        uploaded_at: '2025-01-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'dog-luna',
    name: 'Luna',
    breed: 'Dobermann',
    colour: 'red/rust',
    sex: 'female',
    date_of_birth: '2025-03-15',
    father_id: 'dog-zeus',
    mother_id: 'dog-nala',
    microchip_number: null,
    status: 'reserved',
    category: 'puppy',
    price: 65000,
    bloodline: 'kennel_own',
    health_tested: false,
    hip_score: null,
    elbow_score: null,
    dcm_status: 'clear',
    pedigree_url: null,
    description: 'Standout female puppy from the spring litter. Reserved.',
    temperament_notes: 'Bold, curious and people-oriented.',
    training_notes: 'Early neurological stimulation completed.',
    is_featured: false,
    is_public: true,
    created_at: '2025-03-20T00:00:00Z',
    updated_at: '2025-03-20T00:00:00Z',
    media: [
      {
        id: 'm-luna-1',
        dog_id: 'dog-luna',
        type: 'photo',
        url: img('photo-1583337130417-3346a1be7dee'),
        thumbnail_url: null,
        caption: 'Luna',
        is_primary: true,
        sort_order: 0,
        uploaded_at: '2025-03-20T00:00:00Z',
      },
    ],
  },
];

export const MOCK_LITTERS: Litter[] = [
  {
    id: 'litter-a',
    name: 'A-Litter (Zeus \u00d7 Nala)',
    litter_letter: 'A',
    mother_id: 'dog-nala',
    father_id: 'dog-zeus',
    whelping_type: null,
    expected_date: '2026-08-01',
    actual_date: null,
    actual_time: null,
    go_home_date: '2026-10-01',
    puppy_count: null,
    male_count: null,
    female_count: null,
    available_count: 6,
    description:
      'A repeat of our most successful pairing. Expecting black/rust and red/rust puppies of exceptional working and family potential.',
    status: 'expected',
    is_public: true,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    client_name: 'Andre M.',
    location: 'Pretoria, ZA',
    dog_name: 'Zeus',
    content:
      'The handover was world-class. Our dog integrated into the family within days and the obedience is flawless. This is a different level of breeding and training.',
    video_url: null,
    photo_url: null,
    is_featured: true,
    is_approved: true,
    sort_order: 0,
    created_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 't-2',
    client_name: 'Sarah K.',
    location: 'Cape Town, ZA',
    dog_name: 'Nala',
    content:
      'Calm in the home, switched-on when it matters. Exactly what was promised. The aftercare and support have been outstanding.',
    video_url: null,
    photo_url: null,
    is_featured: true,
    is_approved: true,
    sort_order: 1,
    created_at: '2025-07-01T00:00:00Z',
  },
];

export const MOCK_GALLERY: GalleryItem[] = [
  {
    id: 'g-1',
    title: 'Spring litter',
    description: null,
    image_url: img('photo-1583337130417-3346a1be7dee'),
    video_url: null,
    category: 'puppies',
    is_featured: true,
    sort_order: 0,
    created_at: '2025-03-20T00:00:00Z',
  },
  {
    id: 'g-2',
    title: 'Protection foundation',
    description: null,
    image_url: img('photo-1518717758536-85ae29035b6d'),
    video_url: null,
    category: 'training',
    is_featured: false,
    sort_order: 1,
    created_at: '2025-04-20T00:00:00Z',
  },
  {
    id: 'g-3',
    title: 'In the home',
    description: null,
    image_url: img('photo-1605568427561-40dd23c2acea'),
    video_url: null,
    category: 'family',
    is_featured: false,
    sort_order: 2,
    created_at: '2025-05-20T00:00:00Z',
  },
  {
    id: 'g-4',
    title: 'Kennel grounds',
    description: null,
    image_url: img('photo-1568572933382-74d440642117'),
    video_url: null,
    category: 'kennel',
    is_featured: false,
    sort_order: 3,
    created_at: '2025-05-21T00:00:00Z',
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    dog_id: 'dog-zeus',
    title: 'IGP1 — Schutzhund Title',
    trial_date: '2023-09-10',
    location: 'Gauteng Working Dog Club',
    judge: 'M. Botha',
    score: '96 / 95 / 98',
    notes: 'Excellent tracking and protection phase.',
    created_at: '2023-09-11T00:00:00Z',
  },
  {
    id: 'ach-2',
    dog_id: 'dog-nala',
    title: 'Breed Survey — Class 1',
    trial_date: '2023-05-02',
    location: 'Dobermann Club SA',
    judge: 'P. van Wyk',
    score: 'V (Excellent)',
    notes: 'Outstanding conformation and temperament assessment.',
    created_at: '2023-05-03T00:00:00Z',
  },
];

export const MOCK_CLIENTS: AppUser[] = [
  {
    id: 'user-andre',
    full_name: 'Andre Meyer',
    phone: '+27 82 000 0001',
    country: 'South Africa',
    city: 'Pretoria',
    address: null,
    whatsapp_number: null,
    dog_experience: null,
    current_pets: null,
    has_children: null,
    property_type: null,
    has_fencing: null,
    purpose: null,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    emergency_contact_relationship: null,
    vet_practice: null,
    vet_name: null,
    vet_phone: null,
    profile_completed_at: null,
    role: 'client',
    avatar_url: null,
    marketing_opt_in: true,
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: 'user-sarah',
    full_name: 'Sarah King',
    phone: '+27 83 000 0002',
    country: 'South Africa',
    city: 'Cape Town',
    address: null,
    whatsapp_number: null,
    dog_experience: null,
    current_pets: null,
    has_children: null,
    property_type: null,
    has_fencing: null,
    purpose: null,
    emergency_contact_name: null,
    emergency_contact_phone: null,
    emergency_contact_relationship: null,
    vet_practice: null,
    vet_name: null,
    vet_phone: null,
    profile_completed_at: null,
    role: 'client',
    avatar_url: null,
    marketing_opt_in: false,
    created_at: '2025-02-14T00:00:00Z',
    updated_at: '2025-02-14T00:00:00Z',
  },
];

export const MOCK_APP_SETTINGS: AppSettings = {
  whatsapp_number: '+27 82 000 0000',
  whatsapp_community_url: 'https://chat.whatsapp.com/example',
  telegram_channel_url: 'https://t.me/diedericksdobermanns',
  facebook_page_url: 'https://facebook.com/diedericksdobermanns',
  instagram_url: 'https://instagram.com/diedericksdobermanns',
  youtube_url: 'https://youtube.com/@diedericksdobermanns',
};

export const MOCK_CLIENT_GROUPS: ClientGroup[] = [
  {
    id: 'group-litter-a',
    name: 'Litter — Apollo x Athena',
    type: 'litter',
    litter_id: 'litter-a',
    created_at: '2026-05-01T00:00:00Z',
    member_count: 2,
    last_message_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'group-training',
    name: 'Protection Training Clients',
    type: 'training',
    litter_id: null,
    created_at: '2026-03-01T00:00:00Z',
    member_count: 1,
    last_message_at: null,
  },
  {
    id: 'group-all',
    name: 'All Clients',
    type: 'all_clients',
    litter_id: null,
    created_at: '2026-01-01T00:00:00Z',
    member_count: 2,
    last_message_at: '2026-06-10T12:00:00Z',
  },
];

export const MOCK_GROUP_MEMBERS: ClientGroupMember[] = [
  { id: 'gm-1', group_id: 'group-litter-a', client_id: 'user-andre', added_at: '2026-05-02T00:00:00Z', client: MOCK_CLIENTS[0] },
  { id: 'gm-2', group_id: 'group-litter-a', client_id: 'user-sarah', added_at: '2026-05-03T00:00:00Z', client: MOCK_CLIENTS[1] },
  { id: 'gm-3', group_id: 'group-training', client_id: 'user-sarah', added_at: '2026-03-05T00:00:00Z', client: MOCK_CLIENTS[1] },
  { id: 'gm-4', group_id: 'group-all', client_id: 'user-andre', added_at: '2026-01-02T00:00:00Z', client: MOCK_CLIENTS[0] },
  { id: 'gm-5', group_id: 'group-all', client_id: 'user-sarah', added_at: '2026-01-02T00:00:00Z', client: MOCK_CLIENTS[1] },
];

export const MOCK_BROADCASTS: BroadcastMessage[] = [
  {
    id: 'bc-1',
    group_id: 'group-litter-a',
    title: 'Puppies are 6 weeks old!',
    body: 'Big milestone this week — first vaccinations done and temperament testing has begun. Photos to follow. Pickup is still on track for August.',
    image_url: img('photo-1583511655857-d19b40a7a54e'),
    channels: ['push', 'whatsapp'],
    status: 'sent',
    scheduled_for: null,
    sent_at: '2026-06-15T09:00:00Z',
    sent_by: null,
    created_at: '2026-06-15T09:00:00Z',
    group: MOCK_CLIENT_GROUPS[0],
    read_at: null,
  },
  {
    id: 'bc-2',
    group_id: 'group-all',
    title: 'New website & client portal is live',
    body: 'You can now track your dog, view documents, and message us directly from the app. Welcome aboard!',
    image_url: null,
    channels: ['push'],
    status: 'sent',
    scheduled_for: null,
    sent_at: '2026-06-10T12:00:00Z',
    sent_by: null,
    created_at: '2026-06-10T12:00:00Z',
    group: MOCK_CLIENT_GROUPS[2],
    read_at: '2026-06-10T18:00:00Z',
  },
];

// Training booking system ---------------------------------------------------
export const MOCK_SESSION_TYPES: TrainingSessionType[] = [
  {
    id: 'st-consult',
    name: 'Video Consultation',
    description: 'A 30-minute video call to discuss your dog, training goals or a prospective placement.',
    duration_minutes: 30,
    price: 0,
    currency: 'ZAR',
    session_format: 'video_call',
    is_active: true,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'st-obedience',
    name: 'Obedience Session',
    description: 'In-person obedience training at the kennel. Bring your dog and lead.',
    duration_minutes: 60,
    price: 650,
    currency: 'ZAR',
    session_format: 'in_person',
    is_active: true,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'st-protection',
    name: 'Protection Assessment',
    description: 'Evaluation of drive, nerve and suitability for protection work. In person or video.',
    duration_minutes: 90,
    price: 1200,
    currency: 'ZAR',
    session_format: 'both',
    is_active: true,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'st-video-review',
    name: 'Video Review',
    description: 'Send us footage beforehand and we review it together on a call.',
    duration_minutes: 45,
    price: 450,
    currency: 'ZAR',
    session_format: 'video_call',
    is_active: true,
    sort_order: 4,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const MOCK_AVAILABILITY: TrainingAvailability[] = [
  { id: 'av-1', available_date: dayOffset(1), start_time: '09:00', end_time: '09:30', session_type_id: null, trainer_id: null, max_bookings: 1, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
  { id: 'av-2', available_date: dayOffset(1), start_time: '10:00', end_time: '11:00', session_type_id: 'st-obedience', trainer_id: null, max_bookings: 1, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
  { id: 'av-3', available_date: dayOffset(2), start_time: '14:00', end_time: '14:45', session_type_id: 'st-video-review', trainer_id: null, max_bookings: 2, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 1 },
  { id: 'av-4', available_date: dayOffset(3), start_time: '08:00', end_time: '09:30', session_type_id: 'st-protection', trainer_id: null, max_bookings: 1, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
  { id: 'av-5', available_date: dayOffset(3), start_time: '11:00', end_time: '11:30', session_type_id: null, trainer_id: null, max_bookings: 1, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
  { id: 'av-6', available_date: dayOffset(5), start_time: '15:00', end_time: '15:30', session_type_id: 'st-consult', trainer_id: null, max_bookings: 1, is_blocked: false, notes: null, created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
  { id: 'av-7', available_date: dayOffset(6), start_time: '10:00', end_time: '11:00', session_type_id: 'st-obedience', trainer_id: null, max_bookings: 1, is_blocked: true, notes: 'Trainer unavailable', created_at: '2026-06-01T00:00:00Z', booked_count: 0 },
];

export const MOCK_TRAINING_BOOKINGS: TrainingBooking[] = [
  {
    id: 'tb-1',
    client_id: 'user-andre',
    session_type_id: 'st-consult',
    availability_id: 'av-6',
    dog_id: null,
    trainer_id: null,
    scheduled_at: `${dayOffset(5)}T15:00:00Z`,
    duration_minutes: 30,
    session_format: 'video_call',
    status: 'confirmed',
    client_notes: 'Want to discuss adding a second dog.',
    trainer_notes: null,
    admin_notes: null,
    cancellation_reason: null,
    cancelled_by: null,
    cancelled_at: null,
    confirmed_at: '2026-06-18T00:00:00Z',
    completed_at: null,
    reminder_sent: false,
    video_room_name: 'dd-session-tb1',
    video_room_url: 'https://meet.google.com/abc-defg-hij',
    video_host_url: null,
    video_room_expires_at: `${dayOffset(5)}T16:00:00Z`,
    created_at: '2026-06-17T00:00:00Z',
    updated_at: '2026-06-18T00:00:00Z',
    session_type: MOCK_SESSION_TYPES[0],
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'tb-2',
    client_id: 'user-andre',
    session_type_id: 'st-obedience',
    availability_id: 'av-2',
    dog_id: MOCK_DOGS[0]?.id ?? null,
    trainer_id: null,
    scheduled_at: `${dayOffset(1)}T10:00:00Z`,
    duration_minutes: 60,
    session_format: 'in_person',
    status: 'pending',
    client_notes: 'Working on loose-lead walking.',
    trainer_notes: null,
    admin_notes: null,
    cancellation_reason: null,
    cancelled_by: null,
    cancelled_at: null,
    confirmed_at: null,
    completed_at: null,
    reminder_sent: false,
    video_room_name: null,
    video_room_url: null,
    video_host_url: null,
    video_room_expires_at: null,
    created_at: '2026-06-20T00:00:00Z',
    updated_at: '2026-06-20T00:00:00Z',
    session_type: MOCK_SESSION_TYPES[1],
    dog: MOCK_DOGS[0] ?? null,
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'tb-3',
    client_id: 'user-andre',
    session_type_id: 'st-video-review',
    availability_id: null,
    dog_id: MOCK_DOGS[0]?.id ?? null,
    trainer_id: null,
    scheduled_at: `${dayOffset(-10)}T14:00:00Z`,
    duration_minutes: 45,
    session_format: 'video_call',
    status: 'completed',
    client_notes: 'Reviewed bite-work footage.',
    trainer_notes: 'Good grip development. Continue tug routine 3x weekly.',
    admin_notes: null,
    cancellation_reason: null,
    cancelled_by: null,
    cancelled_at: null,
    confirmed_at: '2026-06-05T00:00:00Z',
    completed_at: `${dayOffset(-10)}T14:45:00Z`,
    reminder_sent: true,
    video_room_name: null,
    video_room_url: null,
    video_host_url: null,
    video_room_expires_at: null,
    created_at: '2026-06-04T00:00:00Z',
    updated_at: `${dayOffset(-10)}T14:45:00Z`,
    session_type: MOCK_SESSION_TYPES[3],
    dog: MOCK_DOGS[0] ?? null,
    client: MOCK_CLIENTS[0],
    media: [
      { id: 'tbm-1', booking_id: 'tb-3', media_type: 'image', storage_path: '', public_url: img('photo-1568572933382-74d440642117'), caption: 'Grip work', uploaded_by: null, created_at: `${dayOffset(-10)}T15:00:00Z` },
    ],
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    user_id: 'user-andre',
    full_name: 'Andre Meyer',
    date_of_birth: '15/03/1985',
    email: 'andre@example.com',
    phone: '+27 82 000 0001',
    id_number: '8503155800088',
    occupation: 'Business owner',
    employer: 'Meyer Security',
    country: 'South Africa',
    province: 'Gauteng',
    city: 'Pretoria',
    address: '12 Oak Street, Pretoria',
    instagram_handle: '@andremeyer',
    facebook_profile: null,
    dog_interest: 'protection_dog',
    specific_dog_id: 'dog-titan',
    litter_interest_id: null,
    purpose: 'protection',
    experience_with_dobermanns: 'Owned two Dobermanns previously.',
    current_pets: 'None',
    home_type: 'house',
    has_secure_yard: 'yes',
    yard_size: 'large_500_plus',
    sleeping_arrangement: 'inside_lounge',
    hours_alone_per_day: '2_4',
    exercise_level: 'very_active',
    why_dobermann: 'Family protection on our smallholding.',
    dobermann_experience_level: 'previous_owner',
    aware_of_dcm: 'yes_fully_aware',
    aware_of_commitment: 'yes_fully_prepared',
    aware_of_costs: 'yes_fully_budgeted',
    previous_dog_fate: null,
    preferred_sex: 'male',
    preferred_colour: 'black_tan',
    tail_preference: 'docked',
    preferred_timeline: '3_months',
    budget_range: 'elite',
    training_planned: true,
    delivery_acknowledged: true,
    special_requests: null,
    children_ages: '9, 12',
    security_requirements: 'Family protection on a smallholding.',
    vet_name: 'Dr. Naidoo',
    vet_phone: '+27 12 000 0000',
    personal_reference_name: 'J. Pretorius',
    personal_reference_phone: '+27 82 111 2222',
    status: 'submitted',
    admin_notes: null,
    reviewed_by: null,
    reviewed_at: null,
    agreed_no_breeding_rights: true,
    agreed_right_of_recall: true,
    agreed_no_resale: true,
    agreed_welfare_commitment: true,
    agreed_microchip_policy: true,
    agreed_to_terms: true,
    created_at: '2026-06-15T09:00:00Z',
    updated_at: '2026-06-15T09:00:00Z',
  },
  {
    id: 'app-2',
    user_id: 'user-sarah',
    full_name: 'Sarah King',
    date_of_birth: '22/07/1990',
    email: 'sarah@example.com',
    phone: '+27 83 000 0002',
    id_number: null,
    occupation: 'Architect',
    employer: null,
    country: 'South Africa',
    province: 'Western Cape',
    city: 'Cape Town',
    address: '45 Sea Point Rd, Cape Town',
    instagram_handle: null,
    facebook_profile: null,
    dog_interest: 'elite_developed',
    specific_dog_id: null,
    litter_interest_id: 'litter-a',
    purpose: 'family',
    experience_with_dobermanns: 'First-time Dobermann owner, experienced with large breeds.',
    current_pets: '1 Labrador',
    home_type: 'house',
    has_secure_yard: 'yes',
    yard_size: 'medium_200_500',
    sleeping_arrangement: 'inside_bedroom',
    hours_alone_per_day: '4_6',
    exercise_level: 'active',
    why_dobermann: 'Looking for a loyal family companion.',
    dobermann_experience_level: 'researched_only',
    aware_of_dcm: 'aware_learning_more',
    aware_of_commitment: 'mostly_prepared',
    aware_of_costs: 'mostly_prepared',
    previous_dog_fate: 'Labrador still alive, age 5',
    preferred_sex: 'female',
    preferred_colour: 'no_preference',
    tail_preference: 'natural',
    preferred_timeline: 'next_litter',
    budget_range: 'standard',
    training_planned: false,
    delivery_acknowledged: true,
    special_requests: null,
    children_ages: 'None',
    security_requirements: null,
    vet_name: null,
    vet_phone: null,
    personal_reference_name: null,
    personal_reference_phone: null,
    status: 'under_review',
    admin_notes: 'Strong candidate. Awaiting reference check.',
    reviewed_by: null,
    reviewed_at: null,
    agreed_no_breeding_rights: true,
    agreed_right_of_recall: true,
    agreed_no_resale: true,
    agreed_welfare_commitment: true,
    agreed_microchip_policy: true,
    agreed_to_terms: true,
    created_at: '2026-06-12T14:30:00Z',
    updated_at: '2026-06-13T08:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: NotificationLog[] = [
  {
    id: 'notif-1',
    recipient_id: 'user-andre',
    type: 'push',
    subject: 'Reservation confirmed',
    body: 'Your reservation for Luna has been confirmed. Estimated pickup: Aug 2026.',
    status: 'delivered',
    sent_at: '2026-06-18T08:30:00Z',
  },
  {
    id: 'notif-2',
    recipient_id: 'user-andre',
    type: 'push',
    subject: 'Training milestone',
    body: 'Luna completed her foundation obedience module.',
    status: 'delivered',
    sent_at: '2026-06-12T15:00:00Z',
  },
  {
    id: 'notif-3',
    recipient_id: 'user-andre',
    type: 'email',
    subject: 'Vaccination reminder',
    body: 'Luna’s next vaccination is due 12 Jul 2026.',
    status: 'sent',
    sent_at: '2026-06-05T09:00:00Z',
  },
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'contract-1',
    reservation_id: 'res-1',
    client_id: 'user-andre',
    dog_id: 'dog-titan',
    document_url: 'https://example.com/contracts/titan-purchase-agreement.pdf',
    signed_by_client: false,
    signed_at: null,
    notes: 'Purchase agreement — awaiting your signature.',
    created_at: '2026-06-16T00:00:00Z',
  },
  {
    id: 'contract-2',
    reservation_id: 'res-1',
    client_id: 'user-andre',
    dog_id: 'dog-titan',
    document_url: 'https://example.com/contracts/health-guarantee.pdf',
    signed_by_client: true,
    signed_at: '2026-06-10T00:00:00Z',
    notes: 'Health guarantee — signed.',
    created_at: '2026-06-08T00:00:00Z',
  },
];

export const MOCK_WAITING_LIST: WaitingListEntry[] = [
  {
    id: 'wl-1',
    client_id: 'user-sarah',
    list_type_id: null,
    application_id: null,
    litter_id: 'litter-a',
    enquirer_name: null,
    enquirer_email: null,
    enquirer_phone: null,
    enquirer_country: null,
    source: 'app',
    preferred_category: 'standard',
    preferred_sex: 'female',
    preferred_colour: 'black/rust',
    ear_preference: 'no_preference',
    tail_preference: 'no_preference',
    registration_preference: null,
    priority: 'high',
    payment_status: 'deposit_paid',
    deposit_amount: 5000,
    quoted_price: null,
    quote_expires_at: null,
    deposit_invoice_id: null,
    assigned_dog_id: null,
    assigned_litter_id: 'litter-a',
    last_contact_date: null,
    preference_notes: 'Female, family companion. Prefers black/rust.',
    admin_notes: null,
    client_visible_note: null,
    internal_flags: ['VIP'],
    do_not_sell_reason: null,
    position: 1,
    status: 'offered',
    pipeline_stage: 'reserved',
    follow_up_date: '2026-06-20',
    feedback: 'Deposit paid. Thrilled with progress photos — confirmed she wants pick of litter.',
    expected_delivery_date: '2026-08-15',
    created_at: '2026-03-01T00:00:00Z',
    client: MOCK_CLIENTS[1],
  },
  {
    id: 'wl-2',
    client_id: 'user-andre',
    list_type_id: null,
    application_id: null,
    litter_id: 'litter-a',
    enquirer_name: null,
    enquirer_email: null,
    enquirer_phone: null,
    enquirer_country: null,
    source: 'referral',
    preferred_category: 'protection',
    preferred_sex: 'male',
    preferred_colour: null,
    ear_preference: 'no_preference',
    tail_preference: 'no_preference',
    registration_preference: null,
    priority: 'normal',
    payment_status: 'deposit_paid',
    deposit_amount: 5000,
    quoted_price: null,
    quote_expires_at: null,
    deposit_invoice_id: null,
    assigned_dog_id: null,
    assigned_litter_id: null,
    last_contact_date: null,
    preference_notes: 'Male, protection prospect.',
    admin_notes: null,
    client_visible_note: null,
    internal_flags: [],
    do_not_sell_reason: null,
    position: 2,
    status: 'active',
    pipeline_stage: 'deposit_paid',
    follow_up_date: null,
    feedback: 'Awaiting temperament assessment at 7 weeks before final allocation.',
    expected_delivery_date: null,
    created_at: '2026-03-12T00:00:00Z',
    client: MOCK_CLIENTS[0],
  },
];

export const MOCK_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    full_name: 'James Liu',
    email: 'james@example.com',
    phone: '+27 84 000 0003',
    subject: 'Availability of red/rust males',
    message: 'Do you have any red/rust males expected in the next litter?',
    dog_id: null,
    country: 'South Africa',
    status: 'new',
    admin_notes: null,
    replied_by: null,
    replied_at: null,
    created_at: '2026-06-17T11:00:00Z',
  },
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'quote-1001',
    quote_number: 'Q-2026-1001',
    client_id: 'user-andre',
    application_id: 'app-1',
    status: 'sent',
    currency: 'ZAR',
    subtotal: 312000,
    discount: 0,
    total: 312000,
    notes: 'Elite Family Protection package. Quote valid for 14 days.',
    valid_until: '2026-07-05',
    created_at: '2026-06-21T09:00:00Z',
    updated_at: '2026-06-21T09:00:00Z',
    client: MOCK_CLIENTS[0],
    items: [
      {
        id: 'qi-1',
        item_type: 'dog',
        dog_id: 'dog-titan',
        description: 'Titan — Elite Family Protection Dog',
        quantity: 1,
        unit_price: 285000,
        line_total: 285000,
        sort_order: 0,
      },
      {
        id: 'qi-2',
        item_type: 'board_train',
        dog_id: null,
        description: 'Board & Train — 4 week handover programme',
        quantity: 1,
        unit_price: 18000,
        line_total: 18000,
        sort_order: 1,
      },
      {
        id: 'qi-3',
        item_type: 'delivery',
        dog_id: null,
        description: 'Delivery & handover — Pretoria',
        quantity: 1,
        unit_price: 9000,
        line_total: 9000,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'quote-1002',
    quote_number: 'Q-2026-1002',
    client_id: 'user-sarah',
    application_id: null,
    status: 'paid',
    currency: 'ZAR',
    subtotal: 65000,
    discount: 5000,
    total: 60000,
    notes: 'Puppy reservation — pick of litter, deposit applied.',
    valid_until: '2026-06-30',
    created_at: '2026-05-30T10:00:00Z',
    updated_at: '2026-06-02T10:00:00Z',
    client: MOCK_CLIENTS[1],
    items: [
      {
        id: 'qi-4',
        item_type: 'dog',
        dog_id: 'dog-luna',
        description: 'Female puppy — black/rust, family companion',
        quantity: 1,
        unit_price: 65000,
        line_total: 65000,
        sort_order: 0,
      },
    ],
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-5001',
    invoice_number: 'INV-2026-5001',
    quote_id: 'quote-1002',
    client_id: 'user-sarah',
    status: 'paid',
    currency: 'ZAR',
    subtotal: 65000,
    discount: 5000,
    total: 60000,
    amount_paid: 60000,
    issued_at: '2026-06-02',
    due_date: '2026-06-09',
    paid_at: '2026-06-03T08:30:00Z',
    notes: 'Paid in full. Puppy reserved.',
    created_at: '2026-06-02T10:05:00Z',
    updated_at: '2026-06-03T08:30:00Z',
    client: MOCK_CLIENTS[1],
    items: [
      {
        id: 'ii-1',
        item_type: 'dog',
        dog_id: 'dog-luna',
        description: 'Female puppy — black/rust, family companion',
        quantity: 1,
        unit_price: 65000,
        line_total: 65000,
        sort_order: 0,
      },
    ],
  },
  {
    id: 'inv-5002',
    invoice_number: 'INV-2026-5002',
    quote_id: null,
    client_id: 'user-andre',
    status: 'partial',
    currency: 'ZAR',
    subtotal: 312000,
    discount: 0,
    total: 312000,
    amount_paid: 100000,
    issued_at: '2026-06-21',
    due_date: '2026-07-21',
    paid_at: null,
    notes: 'Deposit received; balance due on collection.',
    created_at: '2026-06-21T09:30:00Z',
    updated_at: '2026-06-22T09:30:00Z',
    client: MOCK_CLIENTS[0],
    items: [
      {
        id: 'ii-2',
        item_type: 'dog',
        dog_id: 'dog-titan',
        description: 'Titan — Elite Family Protection Dog',
        quantity: 1,
        unit_price: 285000,
        line_total: 285000,
        sort_order: 0,
      },
      {
        id: 'ii-3',
        item_type: 'board_train',
        dog_id: null,
        description: 'Board & Train — 4 week handover programme',
        quantity: 1,
        unit_price: 18000,
        line_total: 18000,
        sort_order: 1,
      },
      {
        id: 'ii-4',
        item_type: 'delivery',
        dog_id: null,
        description: 'Delivery & handover — Pretoria',
        quantity: 1,
        unit_price: 9000,
        line_total: 9000,
        sort_order: 2,
      },
    ],
  },
];

export const MOCK_TIMELINE: TimelineEntry[] = [
  {
    id: 'tl-1',
    dog_id: 'dog-titan',
    author_id: null,
    source: 'kennel',
    category: 'milestone',
    entry_date: '2025-01-15',
    title: 'Foundation week complete',
    notes:
      'Titan settled into the kennel beautifully — confident on all surfaces, strong food and toy drive, clean recall starting to shape up.',
    photo_urls: [img('photo-1518717758536-85ae29035b6d'), img('photo-1605568427561-40dd23c2acea')],
    video_url: null,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'tl-2',
    dog_id: 'dog-titan',
    author_id: null,
    source: 'kennel',
    category: 'training',
    entry_date: '2025-02-20',
    title: 'Protection foundation — grip development',
    notes:
      'Full, calm grips on the puppy tug. Excellent prey drive with a clear off-switch. See the short clip below.',
    photo_urls: [img('photo-1552053831-71594a27632d')],
    video_url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    created_at: '2025-02-20T10:00:00Z',
  },
  {
    id: 'tl-3',
    dog_id: 'dog-titan',
    author_id: null,
    source: 'kennel',
    category: 'training',
    entry_date: '2025-03-28',
    title: 'Obedience under distraction',
    notes: 'Heeling and position changes proofed around other dogs and handlers.',
    photo_urls: [img('photo-1583511655857-d19b40a7a54e')],
    video_url: null,
    created_at: '2025-03-28T10:00:00Z',
  },
  {
    id: 'tl-4',
    dog_id: 'dog-luna',
    author_id: 'user-sarah',
    source: 'client',
    category: 'client_update',
    entry_date: '2026-06-10',
    title: 'First weekend at home',
    notes: 'Settling in so well with the family!',
    photo_urls: [img('photo-1568572933382-74d440642117')],
    video_url: null,
    created_at: '2026-06-10T18:00:00Z',
  },
];

export const MOCK_VACCINATIONS: Vaccination[] = [
  {
    id: 'vax-1',
    dog_id: 'dog-luna',
    vaccine_name: 'DHPP (1st)',
    date_administered: '2025-05-12',
    next_due_date: '2025-06-12',
    administered_by: 'Dr. Naidoo',
    batch_number: 'BX-1029',
    notes: null,
    created_at: '2025-05-12T00:00:00Z',
  },
  {
    id: 'vax-2',
    dog_id: 'dog-luna',
    vaccine_name: 'Rabies',
    date_administered: '2025-07-12',
    next_due_date: '2026-07-12',
    administered_by: 'Dr. Naidoo',
    batch_number: 'RB-5521',
    notes: null,
    created_at: '2025-07-12T00:00:00Z',
  },
];

export const MOCK_TRAINING_LOGS: TrainingLog[] = [
  {
    id: 'tl-1',
    dog_id: 'dog-luna',
    trainer_id: null,
    training_type: 'foundation',
    session_date: '2026-05-20',
    duration_minutes: 45,
    milestone: 'Completed foundation obedience module',
    progress_level: 'foundation',
    notes: 'Excellent focus and engagement.',
    video_url: null,
    created_at: '2026-05-20T00:00:00Z',
  },
  {
    id: 'tl-2',
    dog_id: 'dog-luna',
    trainer_id: null,
    training_type: 'socialization',
    session_date: '2026-06-05',
    duration_minutes: 60,
    milestone: 'Confident on novel surfaces and around traffic',
    progress_level: 'intermediate',
    notes: 'Calm, curious and resilient in new environments.',
    video_url: null,
    created_at: '2026-06-05T00:00:00Z',
  },
];

export const MOCK_FAQ: FaqItem[] = [
  {
    id: 'f-1',
    question: 'How do I reserve a puppy or protection dog?',
    answer:
      'Complete the online application. Once approved, a deposit secures your place and we match you with the right dog based on temperament and your needs.',
    category: 'Reservations',
    sort_order: 0,
    is_published: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'f-2',
    question: 'What health testing do you perform?',
    answer:
      'All breeding stock is DCM tested, hip (HD) and elbow (ED) scored, and screened for the conditions relevant to the breed. Results are shared on every dog profile.',
    category: 'Health',
    sort_order: 1,
    is_published: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'f-3',
    question: 'Do you deliver internationally?',
    answer:
      'Yes. Elite Developed Puppies and Family Protection Dogs include personal delivery and a full handover wherever you are located.',
    category: 'Delivery',
    sort_order: 2,
    is_published: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'f-4',
    question: 'What is the difference between your product tiers?',
    answer:
      'Standard Puppies are our quality entry point. Elite Developed Puppies complete a 6-month in-kennel programme. Elite Family Protection Dogs are fully trained and scenario-proofed.',
    category: 'Programmes',
    sort_order: 3,
    is_published: true,
    created_at: '2025-01-01T00:00:00Z',
  },
];
